### ISSUE TITLE
Slug length

### ISSUE THREAD

**Issue by iandoug** [lionel-rowe/phpbb-human-friendly-urls#2]
Hi

Would be nice to configure slug length.

Maybe also "break at word after x chars" ...

Do you consider this safe to use live?

Thanks, Ian

**Comment by iandoug** [comment]
> Do you consider this safe to use live?

Nope.

[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 65: Undefined array key "port"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 70: Undefined array key "fragment"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 71: Undefined array key "query"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 65: Undefined array key "port"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 70: Undefined array key "fragment"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 71: Undefined array key "query"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 65: Undefined array key "port"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 70: Undefined array key "fragment"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 71: Undefined array key "query"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 65: Undefined array key "port"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 70: Undefined array key "fragment"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 71: Undefined array key "query"

**Comment by lionel-rowe** [comment]
> Would be nice to configure slug length.

Should be easy enough to add. Currently it's anything up to 100 chars.

> Maybe also "break at word after x chars" ...

Not sure exactly what this entails — could you give a couple of examples?

---

I've split the PHP error issue off [here](https://github.com/lionel-rowe/phpbb-human-friendly-urls/issues/3).

**Comment by iandoug** [comment]
t=26-and-then-you-have-some-long-topic-title-that-gets-cut-off-mid-wor
vs
t=26-and-then-you-have-some-long-topic-title-that-gets-cut-off-mid

**Comment by lionel-rowe** [comment]
0.1.9-beta (latest pushed version) adds a "Maximum length for URL slugs" option, configurable via ACP > Extensions > Human-Friendly URLs.

I've also implemented the truncate-at-word-boundary thing but haven't made it configurable — seems barely worth doing so as I doubt many people would specifically _prefer_ to truncate mid-word.

**Comment by iandoug** [comment]
Thanks, seems to be working okay now (one test).

Will test more.
