### ISSUE TITLE
Undefined array key "port"

### ISSUE THREAD

**Issue by lionel-rowe** [lionel-rowe/phpbb-human-friendly-urls#3]
> Do you consider this safe to use live?

Nope.

[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 65: Undefined array key "port"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 70: Undefined array key "fragment"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 71: Undefined array key "query"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 65: Undefined array key "port"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 70: Undefined array key "fragment"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 71: Undefined array key "query"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 65: Undefined array key "port"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 70: Undefined array key "fragment"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 71: Undefined array key "query"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 65: Undefined array key "port"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 70: Undefined array key "fragment"
[phpBB Debug] PHP Warning: in file [ROOT]/ext/luoning/humanfriendlyurls/event/main_listener.php on line 71: Undefined array key "query"

_Originally posted by @iandoug in https://github.com/lionel-rowe/phpbb-human-friendly-urls/issues/2#issuecomment-1075250418_

**Comment by lionel-rowe** [comment]
@iandoug Can you tell me a) what PHP version and phpBB version you're using, b) what other extensions you have enabled, and c) what URLs within posts are visible on the page where you get this error?

**Comment by iandoug** [comment]
phpBB  	3.3.7 
PHP version 8.0.16

Running locally at the moment ... getting to know the ropes.

Tons of extensions.

![extensions](https://user-images.githubusercontent.com/12673886/160018169-081458ce-c9df-490e-b79b-fb588247bd15.png)

**Comment by iandoug** [comment]
Will test newer version tomorrow ... 00:08 here now.

**Comment by lionel-rowe** [comment]
Hmm, I wonder if it's just my setup that's suppressing `phpBB Debug` warnings and your setup is configured to show them.

0.1.8-beta (the version I just pushed) should fix it — can you let me know if that works?

**Comment by lionel-rowe** [comment]
@iandoug I'm closing this for now even though I couldn't reproduce it, as the code changes ensure port, fragment, and query will always exist, and you mentioned elsewhere that 0.1.9-beta seems to be working.
